### PR TITLE
Revert removal of views/error.ejs

### PR DESCRIPTION
**Pull request by JBallin**
Currently getting erros when looking for error.ejs which is causing
heroku deployment to fail.

### CODE REVIEW

**Comment by Brechy** [comment]
This will not fix the problem, team will work on a solution to deploy cleanly on heroku with errors.

**Comment by JBallin** [comment]
I'm going to continue working on this PR to try to fix heroku deploy, currently getting this error when reviewing the logs on heroku website:

> 2018-07-05T01:33:27.860727+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 2018-07-05T01:33:27.869849+00:00 app[web.1]: 
> 2018-07-05T01:33:27.870080+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
> 2018-07-05T01:33:27.870221+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2018-07-05T01_33_27_862Z-debug.log
> 2018-07-05T01:33:27.932150+00:00 heroku[web.1]: Process exited with status 1
> 2018-07-05T01:33:27.952048+00:00 heroku[web.1]: State changed from starting to crashed
> 2018-07-05T01:46:44.834178+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=fam-io.herokuapp.com request_id=9ce91831-8225-4f0c-963a-dafc2801ec5d fwd="24.23.232.97" dyno= connect= service= status=503 bytes= protocol=https
> 2018-07-05T01:46:56.410968+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=fam-io.herokuapp.com request_id=18d972de-02a8-4080-901d-2c343fafe47e fwd="24.23.232.97" dyno= connect= service= status=503 bytes= protocol=https
> 2018-07-05T02:01:36.478531+00:00 heroku[web.1]: State changed from crashed to starting
> 2018-07-05T02:01:41.630543+00:00 heroku[web.1]: Starting process with command `npm start`
> 2018-07-05T02:01:45.763047+00:00 app[web.1]: 
> 2018-07-05T02:01:45.763073+00:00 app[web.1]: > fam@0.0.0 start /app
> 2018-07-05T02:01:45.763075+00:00 app[web.1]: > node ./bin/www
> 2018-07-05T02:01:45.763076+00:00 app[web.1]: 
> 2018-07-05T02:01:46.181058+00:00 app[web.1]: /app/node_modules/knex/lib/index.js:43
> 2018-07-05T02:01:46.181095+00:00 app[web.1]:   if (arguments.length === 0 || !config.client && !config.dialect) {
> 2018-07-05T02:01:46.181097+00:00 app[web.1]:                                         ^
> 2018-07-05T02:01:46.181099+00:00 app[web.1]: 
> 2018-07-05T02:01:46.181101+00:00 app[web.1]: TypeError: Cannot read property 'client' of undefined
> 2018-07-05T02:01:46.181102+00:00 app[web.1]:     at Knex (/app/node_modules/knex/lib/index.js:43:41)
> 2018-07-05T02:01:46.181104+00:00 app[web.1]:     at Object.<anonymous> (/app/knex.js:3:29)
> 2018-07-05T02:01:46.181106+00:00 app[web.1]:     at Module._compile (module.js:652:30)
> 2018-07-05T02:01:46.181107+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:663:10)
> 2018-07-05T02:01:46.181108+00:00 app[web.1]:     at Module.load (module.js:565:32)
> 2018-07-05T02:01:46.181110+00:00 app[web.1]:     at tryModuleLoad (module.js:505:12)
> 2018-07-05T02:01:46.181111+00:00 app[web.1]:     at Function.Module._load (module.js:497:3)
> 2018-07-05T02:01:46.181113+00:00 app[web.1]:     at Module.require (module.js:596:17)
> 2018-07-05T02:01:46.181117+00:00 app[web.1]:     at require (internal/module.js:11:18)
> 2018-07-05T02:01:46.181120+00:00 app[web.1]:     at Object.<anonymous> (/app/routes/users.js:3:14)
> 2018-07-05T02:01:46.181121+00:00 app[web.1]:     at Module._compile (module.js:652:30)
> 2018-07-05T02:01:46.181123+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:663:10)
> 2018-07-05T02:01:46.181124+00:00 app[web.1]:     at Module.load (module.js:565:32)
> 2018-07-05T02:01:46.181126+00:00 app[web.1]:     at tryModuleLoad (module.js:505:12)
> 2018-07-05T02:01:46.181127+00:00 app[web.1]:     at Function.Module._load (module.js:497:3)
> 2018-07-05T02:01:46.181129+00:00 app[web.1]:     at Module.require (module.js:596:17)
> 2018-07-05T02:01:46.188156+00:00 app[web.1]: npm ERR! code ELIFECYCLE
> 2018-07-05T02:01:46.188507+00:00 app[web.1]: npm ERR! errno 1
> 2018-07-05T02:01:46.189569+00:00 app[web.1]: npm ERR! fam@0.0.0 start: `node ./bin/www`
> 2018-07-05T02:01:46.189722+00:00 app[web.1]: npm ERR! Exit status 1
> 2018-07-05T02:01:46.189935+00:00 app[web.1]: npm ERR! 
> 2018-07-05T02:01:46.190090+00:00 app[web.1]: npm ERR! Failed at the fam@0.0.0 start script.
> 2018-07-05T02:01:46.190235+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 2018-07-05T02:01:46.219399+00:00 app[web.1]: 
> 2018-07-05T02:01:46.219550+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
> 2018-07-05T02:01:46.219648+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2018-07-05T02_01_46_191Z-debug.log
> 2018-07-05T02:01:46.304211+00:00 heroku[web.1]: State changed from starting to crashed
> 2018-07-05T02:01:46.285256+00:00 heroku[web.1]: Process exited with status 1

**Comment by JBallin** [comment]
@niksseif, changes shouldn't be approved given that I mentioned I'm going to work on this further. Please don't merge PR.

**Comment by JBallin** [comment]
this is good to go! @Brechy @niksseif

**Pull request merged**
